### ISSUE TITLE
Practica con interfaz grafica con interactividad

### ISSUE THREAD

**Issue by Blanca-estela-valerio-rivero** [SistemasTecTlaxiaco/actividad-3-practica-de-interfaz-grafica-con-interactividad-confident-students#1]
[PRACTICA 3_TOPICOS AVANZADOS DE PROGRAMACION.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-de-interfaz-grafica-con-interactividad-confident-students/files/14316888/PRACTICA.3_TOPICOS.AVANZADOS.DE.PROGRAMACION.pdf)

Integrantes del equipo:
Garcia Santiago Sandy Marissa
Sarmiento Ruiz Edgar Mauricio
Valerio Rivero Blanca Estela

**Comment by MarcoRg06** [comment]
De acuerdo a la rúbrica de evaluación, cumple con todos los puntos requeridos.
Calificación 20%.
*Se encontraron algunas faltas de ortografía y de puntuación, pero en general todo está bien*.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
